In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("Total.csv")

C:\Users\amand\AppData\Local\Temp\ipykernel_29912\119456732.py:1: DtypeWarning: Columns (0: BasePay, 1: OvertimePay, 2: OtherPay, 3: Benefits) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("Total.csv")

In [3]:
df.head()

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,Not Provided,567595.43,567595.43,2011
1,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,Not Provided,538909.28,538909.28,2011
2,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,Not Provided,335279.91,335279.91,2011
3,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,Not Provided,332343.61,332343.61,2011
4,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,Not Provided,326373.19,326373.19,2011

In [4]:
df.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year'],
      dtype='str')

In [18]:
def get_employee(name):
    try:
        employee = df[df["EmployeeName"] == name]

        if employee.empty:
            return "Employee not found"

        return employee

    except Exception as e:
        return f"An error occurred: {e}"

In [19]:
df["EmployeeName"].head()

0       NATHANIEL FORD
1         GARY JIMENEZ
2       ALBERT PARDINI
3    CHRISTOPHER CHONG
4      PATRICK GARDNER
Name: EmployeeName, dtype: str

In [22]:
employee = get_employee("NATHANIEL FORD")
employee

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,Not Provided,567595.43,567595.43,2011

In [27]:
employee_dict={
    "Name": employee.iloc[0]["EmployeeName"],
    "Job Title": employee.iloc[0]["JobTitle"],
    "Base Pay": employee.iloc[0]["BasePay"],
    "Overtime Pay": employee.iloc[0]["OvertimePay"],
    "Total Pay": employee.iloc[0]["TotalPay"],
    "Year": employee.iloc[0]["Year"]
}

employee_dict

{'Name': 'NATHANIEL FORD',
 'Job Title': 'GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
 'Base Pay': 167411.18,
 'Overtime Pay': 0.0,
 'Total Pay': np.float64(567595.43),
 'Year': np.int64(2011)}

In [28]:
employee_df =pd.DataFrame([employee_dict])
employee_df.to_csv("employee_details_vanasdall.csv", index=False)
print("Employee details exported successfully!")

Employee details exported successfully!